### ISSUE TITLE
history and monitoring period

### ISSUE THREAD

**Issue by yfinegold** [sepal-contrib/bfast_gpu#18]
Some suggestions for some minor UI changes to make it more intuitive
1. history first, monitoring second
2. Add history end date - that would require subsetting the time series if the history end is before the monitoring start
3. Related point 2 - make the minimum monitoring start date the history end date. 

That's all I can think of for now! :)

**Comment by 12rambau** [comment]
bfast python biding is not accepting an "end date" parameter that's why I use 2 different Slider.
I will adapt the slider default value to make it start at the minimum value
